{% set version = "1.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gap/gap_{{ version }}.tar.gz
  sha256: 9cff9b6f5c83a15fdf49b9bc0e165a596d54f0e246d27447e59931faf690e0df

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-plotly                   # [build_platform != target_platform]
    - r-gap.datasets             # [build_platform != target_platform]
    - r-dplyr                    # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-gap.datasets
    - r-ggplot2
    - r-plotly
  run:
    - r-base
    - r-dplyr
    - r-gap.datasets
    - r-ggplot2
    - r-plotly

test:
  commands:
    - $R -e "library('gap')"           # [not win]
    - "\"%R%\" -e \"library('gap')\""  # [win]

about:
  home: https://github.com/jinghuazhao/R
  license: GPL-2.0-or-later
  summary: It is designed as an integrated package for genetic data analysis of both population and family data. Currently, it contains functions for sample size calculations of both population-based and family-based designs, probability of familial disease aggregation, kinship calculation, statistics in linkage analysis,
    and association analysis involving genetic markers including haplotype analysis with or without environmental covariates.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: gap
# Version: 1.2.1
# Date: 2019-6-5
# Title: Genetic Analysis Package
# Author: Jing Hua Zhao and colleagues with inputs from Kurt Hornik and Brian Ripley
# Maintainer: Jing Hua Zhao <jinghuazhao@hotmail.com>
# URL: https://github.com/jinghuazhao/R
# BugReports: https://github.com/jinghuazhao/R/issues
# Depends: R (>= 2.10)
# Suggests: BradleyTerry2, MASS, Matrix, MCMCglmm, R2jags, bdsmatrix, calibrate, circlize, coda, coxme, dplyr, foreign, forestplot, gap.datasets, grid, haplo.stats, kinship2, lattice, magic, meta, mets, nlme, pedigree, pedigreemm, plotrix, qqman, regress, reshape, rmeta, rms, survival
# LazyData: Yes
# LazyLoad: Yes
# Description: It is designed as an integrated package for genetic data analysis of both population and family data. Currently, it contains functions for sample size calculations of both population-based and family-based designs, probability of familial disease aggregation, kinship calculation, statistics in linkage analysis, and association analysis involving genetic markers including haplotype analysis with or without environmental covariates.
# License: GPL (>= 2)
# NeedsCompilation: yes
# Repository: CRAN
# Packaged: 2019-06-05 10:52:26 UTC; jhz22
# Date/Publication: 2019-06-05 12:00:06 UTC
