{% set version = "1.5-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gap/gap_{{ version }}.tar.gz
  sha256: 6e19f9d822460867fcb97fe917730ce0f87218893a6a7edae42caaa401b452ce

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-plotly                         # [build_platform != target_platform]
    - r-gap.datasets                   # [build_platform != target_platform]
    - r-dplyr                          # [build_platform != target_platform]
    - r-ggplot2                        # [build_platform != target_platform]
    - r-rdpack                         # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-gap.datasets
    - r-ggplot2
    - r-plotly
    - r-rdpack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-dplyr
    - r-gap.datasets
    - r-ggplot2
    - r-plotly
    - r-rdpack

test:
  commands:
    - $R -e "library('gap')"           # [not win]
    - "\"%R%\" -e \"library('gap')\""  # [win]

about:
  home: https://github.com/jinghuazhao/R
  license: GPL-2.0-or-later
  summary: It is designed as an integrated package for genetic data analysis of both population and family data. Currently, it contains functions for sample size calculations of both population-based and family-based designs, probability of familial disease aggregation, kinship calculation, statistics in linkage analysis,
    and association analysis involving genetic markers including haplotype analysis with or without environmental covariates.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
