travis:
  secure:
    BINSTAR_TOKEN: UF7M7upCZYr5wwcnK+B5Ewk9HxVTVp1DaKS2/esTR4q6pznSIumiouTDbjxG3GPRpzIjVQN1j+06DwwZnQ9L2LVNTsLqt3dq+MUddbQBSj0xbjKbBQkE6ZkHdi3t+jR5GQYAOBhvcouX9BBd5F6Mbqn2oCqKeL0wk1F/ZdlPBkmCW9pT25EJ9ghuALpZozOAEStI4Y1Da4Nn0goP38I7bQSh6Cu9v+9OSeBPHaTpm/hJX0KQ4BesJhJojgjUdIuFXBK3Vqa2fWJ4v0iCqFxowHLlKG1E1r48zZlMGd4TL3GfevsRvaEqmun6qLMIJj8vJuzeZzjqroqam6k8Yujpn9fc8ZWcDTiS92qs6nYyyVKJLiyJt4W4ZvrO3Ypf+anxxmqy4fit1H7i5flAWQJsE5vWmUrfmM/Ba0rx1tNPOCk18UaoK7MnclfZxlSsxK9cFIbm3Bnf2lhQsUnFS5ADkIdMULfLTq0juA6utIPdf7Fm12OndwAuOoAIMpNhG/lU/waoROejyiGOPWJECP5DXfVzvHcBmJ8/xlNcSed1s6cGTBDOh0JdtUkrS8/KJZYW1HafdMUfJcLf57SzIMaRC5eevzelE58x4415sfGLQHkog319KnSu5r+qgJIvfUUtaoXX044rfvsQi2/qVQG8lAsMMH1j6mvne+6uL+BmDQk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
